name: auto_app_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  shelf_router:
  shelf:
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
